name: Test deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/docs/**'
      - '.github/workflows/docs-test-deploy.yml'

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build
